version: '3.3'

services:
  frontcompose:
    image: gitlab.labranet.jamk.fi:4567/te-team-2/reactfront:latest
    ports:
      - "8081:4100"
      #- "80:4100"
    restart: always
    environment:
      REACT_APP_API_ROOT:  bittikyylat.devopskoulutus.net:8080/api

  backcompose:
    depends_on:
      - mongocompose
    image: gitlab.labranet.jamk.fi:4567/te-team-2/nodeback:latest
    ports:
      - "8080:3000"
    restart: always
    environment:
      MONGODB_URI: mongodb://mongocompose/conduit
      NODE_ENV: production 
      SECRET: supersalainen
 
  mongocompose:
    image: mongo:4.4.1
    volumes:
      - db_data:/data/db
    restart: always
     
volumes:
    db_data: {}